### ISSUE TITLE
Problems installing package

### ISSUE THREAD

**Issue by GreenGilad** [ShobiStassen/VIA#10]
Hi there,

I have been trying to install the package on both windows (11) computer and a mac computer. In both cases once the library is installed it fails to import because palantir is not installed (which itself fails in installation on MulticoreTSNE).

Why is palantir required for VIA?

```
>>> import pyVIA.core as via
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".....................ViaEnv\lib\site-packages\pyVIA\__init__.py", line 1, in <module>
    from . import core
  File "................\ViaEnv\lib\site-packages\pyVIA\core.py", line 27, in <module>
    import palantir # /home/shobi/anaconda3/envs/ViaEnv/lib/python3.7/site-packages/palantir
ModuleNotFoundError: No module named 'palantir'
```

**Comment by GreenGilad** [comment]
After fixing the `cmake`+`palantir` installations (by downgrading cmake: `pip install cmake==3.18.4`) I managed to import.
However, is palantir installation actually required for VIA? and if perhaps it should be added to the instructions.

Thanks

**Comment by ShobiStassen** [comment]
hi, sorry for the issues you had during installation. Palantir is not required for VIA, but is included in the script for some testing/benchmarking functions I was testing (it seems to have made its way back in the code). I will change this later today so that there is no palantir import. Thanks for raising this.

**Comment by ShobiStassen** [comment]
Hi, the installation should no longer require palantir, thanks for bringing this up. (version pyVIA==0.1.23)

**Comment by GreenGilad** [comment]
Perfect! Thanks for the quick fix
