### ISSUE TITLE
Importing VIA issue

### ISSUE THREAD

**Issue by sidrahmaryam-cyber** [ShobiStassen/VIA#18]
Hello,
I successfully installed via using 
```
pip install pybind11
pip install hnswlib
pip install pyVIA
```
However, when I am importing it, `import pyVIA.core` , it gives me following error:
**ModuleNotFoundError: No module named 'utils_via'**

Can I please know the possible issue? 
Thanks in advance.

**Comment by ShobiStassen** [comment]
@sidrahmaryam-cyber 
Hi Sid,
Thanks a lot for pointing this out to me. The issue should be sorted out now (version 0.1.42). please let me know if you still have trouble running via

**Comment by sidrahmaryam-cyber** [comment]
Thank you so much for your prompt response, and yes it did work out.
However, while proceeding forward with analysis, on this line of code:

```
via.draw_trajectory_gams(Y_phate, super_clus_ds_PCA_loc, v1.labels, v0.labels, v0.edgelist_maxout,
                         v1.x_lazy, v1.alpha_teleport, v1.single_cell_pt_markov, time_labels, knn=v0.knn,
                         final_super_terminal=v1.revised_super_terminal_clusters,
                         sub_terminal_clusters=v1.terminal_clusters,
                         title_str='Markov Hitting Times and Paths', ncomp=ncomps, arrow_width_scale_factor=30)
```

I get error as **TypeError: draw_trajectory_gams() got an unexpected keyword argument 'knn'**
and if I remove it, then for final_super_terminal, sub_terminal_clusters and following.


P.S. - <function pyVIA.core.draw_trajectory_gams(via_coarse, via_fine, embedding, idx=None, title_str='Pseudotime', draw_all_curves=True, arrow_width_scale_factor=15, scatter_size=50, scatter_alpha=0.5, linewidth=1.5, marker_edgewidth=1, cmap_pseudotime='viridis_r', dpi=150, highlight_terminal_states=True)>


Similarly with code line:
```
via.draw_sc_evolution_trajectory_dijkstra(v1, Y_phate, knn_hnsw, v0.full_graph_shortpath,
                                          idx=np.arange(0, input_data.shape[0]))
```

**AttributeError: module 'pyVIA.core' has no attribute 'draw_sc_evolution_trajectory_dijkstra'**

Sorry for so much of the trouble :D 

Also, again thanks a lot for your help.

**Comment by ShobiStassen** [comment]
Hi, are you following the readthedocs tutorials?

**Comment by ShobiStassen** [comment]
@sidrahmaryam-cyber 
these are the updated tutorials: https://pyvia.readthedocs.io/en/latest/Basic%20tutorial.html
let me know if that helps (some of the functions you are calling have been deprecated)

**Comment by sidrahmaryam-cyber** [comment]
Ohh, Okay I will follow the one you suggested. 
I was following this https://github.com/ShobiStassen/VIA/blob/master/Jupyter%20Notebooks/ViaJupyter_EmbryoidBody.ipynb

Thank you so much. :)
