### ISSUE TITLE
string index out of range

### ISSUE THREAD

**Issue by melancholy12** [ShobiStassen/VIA#21]
![image](https://user-images.githubusercontent.com/97800939/196341026-3d7b7d63-2d9c-44e8-9b68-8f8db1c367b9.png)

**Comment by ShobiStassen** [comment]
Hi, it seems like you are initializing the true_label parameter as a single string 'medium'.
If you dont have any annotations for you data then leave it as true_label = None (default) and some random labels will be generated. If you do have some sensible annotations/reference, then this should be a list:
  true_label:list
        list of str/int that correspond to the ground truth or reference annotations. Can also be None when no labels are available
the readthedocs page has lots of examples

**Comment by melancholy12** [comment]
Thanks for the reply. I changed the code, but come across the same issue.
![image](https://user-images.githubusercontent.com/97800939/196343891-66793434-c1a2-4305-b88f-a6ae7fa63b54.png)

**Comment by ShobiStassen** [comment]
hi again :)
seems like your true_label is still true_label='medium'
do you want to label all your cells as 'medium'
true_label expects a  list of n_samples length,

**Comment by ShobiStassen** [comment]
like if you have 10 cells, and know their true_labels (or a some kind of reference) ['hsc, 'mono','hsc',...'ery','hsc']
if not, then leave the true_label parameter empty (no 'medium').... since you expect all the cells to be of type 'medium'

**Comment by melancholy12** [comment]
Thanks for your reply. Let me check it again :)
