### ISSUE TITLE
root_user = None

### ISSUE THREAD

**Issue by Stefan-Stefan1** [ShobiStassen/VIA#24]
Hey guys,
i'm using your tool for plotting the trajectory of single cell atac seq data. The visualisation is awesome, but i have a problem when i want to set the root_user = None. In the 'Basic usage tutorial' you explained it to set it None if the Group label of root is unknown. Tried it many times but always get this TypeError:

    if (comp_i > len(self.root_user) - 1): root_user_ = 0
TypeError: object of type 'NoneType' has no len()

Hope you can help me with this problem. Or maybe you can give me a hint, how to get the root?

**Comment by ShobiStassen** [comment]
hi Stefan!
thank you for catching this, my apologies as this is a bug! 
Unless you have rna velocity, via cannot detect a proper root cell. So you just have to arbitrarily choose a cell index root_user = [0] dataset = "'' OR root_user = ['your best group guess that refers to your true_labels'] dataset='group'
I'll fix this in the code later but for now the workaround would be to pass a dummy root

**Comment by ShobiStassen** [comment]
hey, the new version should sort this out, but it's effectively just providing a dummy root (so you may have already fixed that yourself). thanks for catching this. if you have rna-velocity, you can allow for meaningful auto-detection of the root though

**Comment by emessori** [comment]
Hello! Is it still the case that with root_user = None and no RNA velocity, the algorithm will just pick a dummy root? How is it defined?

Thank you.

**Comment by ShobiStassen** [comment]
Hi Stefan, yes you are right. Without RNA velocity, the user needs to provide a single cell index or group level label (corresponding to a label found in true_label). Leaving the root_user undefined just means a random cell is chosen as the root and all pseudtimes and directions are relative to this randomly set root
