### ISSUE TITLE
Pseudotime in the same cluster

### ISSUE THREAD

**Issue by wangjiawen2013** [ShobiStassen/VIA#30]
Hi,
Do the cells in one cluster have the same pseudotime ?

**Comment by ShobiStassen** [comment]
hi, no the pseudotime of a single cell will be the weighted average of the cluster level pseudotimes of each of its neighboring cells (so at the single cell level a cell may have neighbors from different clusters)

**Comment by wangjiawen2013** [comment]
Do the pseudotime and lineage probability depend on  the PARC cluster labels or they are independently

**Comment by wangjiawen2013** [comment]
and I still confuse about the parameter "preserve_disconnected: if you suspect disconnected trajectories, set this to False". What does this sentence mean ?

**Comment by ShobiStassen** [comment]
Hi, yes the lineage and pseudotime are influenced by the cluster graph which aggregates the single cell edges by cluster. Once the cluster level time and probability are computed, we project back to single cell level.

If you think there should be multiple disconnected components in your data, then set preserve_disconnected = False to prevent the method from trying to reconnect them

**Comment by wangjiawen2013** [comment]
And, Does VIA use PARC clustering of true labels given by the users internally when computing pseudotime ?

**Comment by ShobiStassen** [comment]
You can choose to make clusters based on a list of single cell labels you
provide, you just need to pass this in when initializing via. but  the
Cluster graph with Parc does not use true label to guide the clusters. True
label is purely for reference when plotting.
