### ISSUE TITLE
IndexError: non-empty take from an empty axes

### ISSUE THREAD

**Issue by Stefan-Stefan1** [ShobiStassen/VIA#35]
Hey team,
i was using your tool for several datasets but this error is new to me.

![error_via](https://user-images.githubusercontent.com/60397432/212542359-257a87cb-6d43-466e-a408-12e428209df1.PNG)

I normalized and log transformed the data. The umap result looked like this

![grafik](https://user-images.githubusercontent.com/60397432/212542257-2347049c-42e0-48c5-ac17-f19cd2516c74.png)

**Comment by ShobiStassen** [comment]
Hi Stefan,

A couple of suggestions, it seems like the pruning level is potentially too high as Via is detecting two graph components - so unless this is expected, you can adjust the jac_std_global and dist_std_local to a value between 1.5-3 (3 should incur almost no pruning) and also the cluster_graph_pruning to 1.5-3. if you are indeed looking for multiple components then set preserve_disconnected_after_pruning = True when you initialize Via.
