### ISSUE TITLE
terminal states/cell

### ISSUE THREAD

**Issue by wangjiawen2013** [ShobiStassen/VIA#37]
Hi,
In palantir paper, "the Markov chain is also used to infer terminal states from the data. Palantir identifies terminal states as boundary cells (extrema of diffusion components) that are outliers in the stationary distribution, that is, the states into which the random walks converge (Fig. 1c)".  But sometimes we found that cells with lower/early pseudotime can be identified as terminal cells, which is hard to understand.

In VIA,  The MCMC-refined graph-edges of the lazy-teleporting random walk enable accurate predictions of terminal cell fates through a consensus vote of various vertex connectivity properties derived from the directed graph (Step 3: Consensus vote on terminal states based on vertex connectivity properties of the directed graph). Could you explain how VIA identify terminal states more detailed ? and is it possible for VIA identifying terminal cells with lower/early pseudotime ?

**Comment by ShobiStassen** [comment]
hi again,

 VIA looks at the in/out degree of nodes in the directed graph and also metrics like betweeness and centrality. Terminal states are those with few out-edges, and low betweeness and centrality. The user can also tune the parameter "pseudotime_threshold_TS=40 (40th percentile)" which removes terminal state candidates that have pseudotimes that are below the percentile of pseudotime.
