### ISSUE TITLE
beginner problems?

### ISSUE THREAD

**Issue by dxl3742** [ShobiStassen/VIA#40]
super new beginner to python: I got this error after running the test_pyVIA.py, I havent changed anything in the code except for the folder directories:
    draw_trajectory_gams(via_coarse=v0, via_fine=v0, embedding = embedding)
TypeError: draw_trajectory_gams() got an unexpected keyword argument 'via_coarse'

and this error after running the basic workflow tutorial:
fig, ax, ax2= draw_piechart_graph(via0=v0, type_data='pt', title='Toy multifurcation', cmap='viridis', ax_text=  True, gene_exp='', alpha_edge=0.5, linewidth_edge=1.5, edge_color='green', headwidth_arrow=0.2)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: draw_piechart_graph() got an unexpected keyword argument 'via0'

**Comment by dxl3742** [comment]
Hi Shobi, any help would be greatly appreciated, thanks in advance!

**Comment by ShobiStassen** [comment]
Hi Melanie,

I'll reply in more detail shortly but can you change via0=v0 to
via_object=v0

I changed some of the parameter names recently and haven't updated the
tutorials.



Dr. Shobana Stassen, Ph.D.

**Comment by ShobiStassen** [comment]
@dxl3742 [link to API section](https://pyvia.readthedocs.io/en/latest/api.html#module-VIA.plotting_via)
