### ISSUE TITLE
TypeError: plot_scatter() got an unexpected keyword argument 'categorical'

### ISSUE THREAD

**Issue by searchlie** [ShobiStassen/VIA#44]
Hi, 

I got an error when I specified embedding_type='via-mds' in VIA.
![image](https://github.com/ShobiStassen/VIA/assets/28975498/ca4d36ed-4364-43f2-a590-2036db57a376)

On the other hand, when via_mds was run alone, no error occurred.
![image](https://github.com/ShobiStassen/VIA/assets/28975498/4671ce5b-2ee6-453b-bf84-8b1add16f0db)

**Comment by ShobiStassen** [comment]
@searchlie hey thanks for spotting this.
I'll fix it soon, in the mean time are you able to just got into your core.py file and delete the parameter categorial=categorical inside the plot_scatter() function. It no longer exists.
if you arent' sure how to do it let me know and i'll upload an edited version asap!

**Comment by ShobiStassen** [comment]
ok i just uploaded the fixed version 0.1.87! please let me know if it works for you now
by the way i do suggest running via_mds() on it's own if you arent happy with the visualization when running through v0.run_via()
this function has many parameters which can be important when handling larger datasets, and it's super fast so you can test it out quickly

**Comment by searchlie** [comment]
@ShobiStassen 
I updated to version 0.1.87, but another error occurred during import!
![image](https://github.com/ShobiStassen/VIA/assets/28975498/830c7956-521d-4b25-a42d-daf5510c70f0)

**Comment by ShobiStassen** [comment]
@searchlie Hi can you try now. version 0.1.88

**Comment by searchlie** [comment]
@ShobiStassen 
It worked well! Thanks again for the quick fixes!
![image](https://github.com/ShobiStassen/VIA/assets/28975498/c307411b-a6df-407d-8b83-facfa64ac258)
