### ISSUE TITLE
The result changes even though the random seed is fixed

### ISSUE THREAD

**Issue by searchlie** [ShobiStassen/VIA#45]
Hi, 

Even though the random seed is fixed, the result displayed changes each time I run via.
The code used is from the [BASIC WORKFLOW](https://pyvia.readthedocs.io/en/latest/ViaJupyter_Toy_Multifurcating.html):
```python
#define parameters
ncomps, knn, random_seed, dataset, root_user  =30,20, 42,'toy', ['M1']

v0 = via.VIA(adata_counts.obsm['X_pca'][:, 0:ncomps], true_label, jac_std_global=0.15, dist_std_local=1,
             knn=knn, cluster_graph_pruning_std=1, too_big_factor=0.3, root_user=root_user, preserve_disconnected=True, dataset='group',
             random_seed=random_seed, do_compute_embedding=True, embedding_type='via-umap')#, piegraph_arrow_head_width=0.2,             piegraph_edgeweight_scalingfactor=1.0)
v0.run_VIA()
```
![image](https://github.com/ShobiStassen/VIA/assets/28975498/d39f7772-a5b5-43a5-b75b-8615d98c7166)

I think this wasn't the case in previous versions.
I suspect that a recent update has caused the value of the argument random seed to be ignored.

**Comment by ShobiStassen** [comment]
Hi,

I'll have a closer look this weekend, but it seems like it's the embedding
orientation and not the TI results that are changing? The terminal state
cells seem the same in both runs, and instead the randomness is just the
orientation of the scatter plot. You could consider saving an embedding you
like and using it for future runs too

**Comment by ShobiStassen** [comment]
hi @searchlie 
do you mind checking if it works for you now (v = 0.1.89)
thank you!

**Comment by searchlie** [comment]
@ShobiStassen 
I can now reproduce the results successfully!
Thanks again for your quick response!
